export const datatopic = [
  {
    id: 1,
    dsatopic: "Array",
    text: "Array is a collection of similar data elements stored at contiguous memory locations.",
    link: "https://www.geeksforgeeks.org/array-data-structure/",
    url: "/array",
  },
  {
    id: 2,
    dsatopic: "Matrix",
    text: "A matrix is a two-dimensional array that consists of rows and columns. It is an arrangement of elements in horizontal or vertical lines of entries.",
    link: "https://www.geeksforgeeks.org/matrix/",
    url: "/matrix",
  },
  {
    id: 3,
    dsatopic: "String",
    text: "String is a collection of characters stored as an array.",
    link: "https://www.geeksforgeeks.org/string-data-structure/",
    url: "/string",
  },
  {
    id: 4,
    dsatopic: "Searching & Sorting",
    text: "Searching & Sorting is a way of arranging and finding items in a collection.",
    link: "https://www.geeksforgeeks.org/searching-and-sorting/",
    url: "/searchingsorting",
  },
  {
    id: 5,
    dsatopic: "LinkedList",
    text: "Linked list is a linear collection of data elements whose order is not given by their physical placement in memory.",
    link: "https://www.geeksforgeeks.org/data-structures/linked-list/",
    url: "/linkedlist",
  },
  {
    id: 6,
    dsatopic: "Binary Trees",
    text: "Binary tree is a tree-type non-linear data structure with a maximum of two children for each parent.",
    link: "https://www.geeksforgeeks.org/binary-tree-data-structure/",
    url: "/binarytree",
  },
  {
    id: 7,
    dsatopic: "Binary Search Trees",
    text: "What will happen if we mix Binary tree and Binary search? Hmm, something complex? Or not?",
    link: "https://www.geeksforgeeks.org/binary-search-tree-data-structure/",
    url: "/binarysearchtree",
  },
  {
    id: 8,
    dsatopic: "Greedy Algorithm",
    text: "Greedy algorithm is an approach for solving a problem by selecting the best option available at the moment. Do you think it's the best moment to slove these problems?",
    link: "https://www.geeksforgeeks.org/greedy-algorithms/",
    url: "/greedyalgorithm",
  },

  {
    id: 9,
    dsatopic: "BackTracking",
    text: "Backtracking algorithm is a problem-solving algorithm that uses a brute force approach for finding the desired output.",
    link: "https://www.geeksforgeeks.org/backtracking-algorithms/",
    url: "/backtracking",
  },
  {
    id: 10,
    dsatopic: "Stacks and Queues",
    text: "Stack follows LIFO while Queue follows FIFO data structure type. ",
    link: "https://www.geeksforgeeks.org/difference-between-stack-and-queue-data-structures/",
    url: "/stack-queues",
  },
  {
    id: 11,
    dsatopic: "Heap",
    text: "Heap is a specialized tree-based data structure which is essentially an almost complete tree that satisfies the heap property",
    link: "https://www.geeksforgeeks.org/heap-data-structure/",
    url: "/heap",
  },
  {
    id: 12,
    dsatopic: "Graph",
    text: "Enough of linear data structure. Let's get lost in different routes.",
    link: "https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/",
    url: "/graph",
  },
  {
    id: 13,
    dsatopic: "Trie",
    text: "Hard to explain. Why don't you people understand and tell it to me through our contact page?",
    link: "https://www.geeksforgeeks.org/trie-insert-and-search/",
    url: "/trie",
  },
  {
    id: 14,
    dsatopic: "Dynamic Programming",
    text: "Dynamic Programming is mainly an optimization over plain recursion. ",
    link: "https://www.geeksforgeeks.org/dynamic-programming/",
    url: "/dp",
  },
  {
    id: 15,
    dsatopic: "Bit Manipulation",
    text: "It involves converting integers between various bases and manipulating individual bits using bitwise operators.",
    link: "https://www.geeksforgeeks.org/all-about-bit-manipulation/",
    url: "/bitmanipulation",
  },
];
