export const dsatopics = [
  {
    id: 1,
    dsatopic: "Array-I",
    problem: "Set Matrix Zeroes",
    Done: "<->",
    URL: "https://leetcode.com/problems/set-matrix-zeroes/",
  },
  {
    id: 2,
    dsatopic: "Array-I",
    problem: "Pascal's Triangle",
    Done: "<->",
    URL: "https://leetcode.com/problems/pascals-triangle/",
  },
  {
    id: 3,
    dsatopic: "Array-I",
    problem: "Next Permutation",
    Done: "<->",
    URL: "https://leetcode.com/problems/next-permutation/",
  },
  {
    id: 4,
    dsatopic: "Array-I",
    problem: "Kadane’s Algorithm",
    Done: "<->",
    URL: "https://leetcode.com/problems/maximum-subarray/",
  },
  {
    id: 5,
    dsatopic: "Array-I",
    problem: "	Sort an array of 0’s 1’s 2’s",
    Done: "<->",
    URL: "https://leetcode.com/problems/sort-colors/",
  },
  {
    id: 6,
    dsatopic: "Array-I",
    problem: "Best Time to Buy and Sell Stock",
    Done: "<->",
    URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
  },

  {
    id: 7,
    dsatopic: "Array-II",
    problem: "Rotate Image",
    Done: "<->",
    URL: "https://leetcode.com/problems/rotate-image/",
  },
  {
    id: 8,
    dsatopic: "Array-II",
    problem: "Merge Overlapping Subintervals",
    Done: "<->",
    URL: "https://leetcode.com/problems/merge-intervals/",
  },
  {
    id: 9,
    dsatopic: "Array-II",
    problem: "Merge two sorted Arrays without extra space",
    Done: "<->",
    URL: "https://leetcode.com/problems/merge-sorted-array/",
  },
  {
    id: 10,
    dsatopic: "Array-II",
    problem: "Find the duplicate in an array of N+1 integers.",
    Done: "<->",
    URL: "https://leetcode.com/problems/find-the-duplicate-number/",
  },
  {
    id: 11,
    dsatopic: "Array-II",
    problem: "Repeat and Missing Number",
    Done: "<->",
    URL: "https://www.interviewbit.com/problems/repeat-and-missing-number-array/",
  },
  {
    id: 12,
    dsatopic: "Array-III",
    problem: "Search in a 2d Matrix",
    Done: "<->",
    URL: "https://leetcode.com/problems/search-a-2d-matrix/",
  },
  {
    id: 13,
    dsatopic: "Array-III",
    problem: "Pow(X,n)",
    Done: "<->",
    URL: "https://leetcode.com/problems/powx-n/",
  },
  {
    id: 14,
    dsatopic: "Array-III",
    problem: "Majority Element (>N/2 times)",
    Done: "<->",
    URL: "https://leetcode.com/problems/majority-element/",
  },
  {
    id: 15,
    dsatopic: "Array-III",
    problem: "Majority Element (>N/3 times)",
    Done: "<->",
    URL: "https://leetcode.com/problems/majority-element-ii/",
  },
  {
    id: 16,
    dsatopic: "Array-III",
    problem: "Grid Unique Paths",
    Done: "<->",
    URL: "https://leetcode.com/problems/unique-paths/",
  },
  {
    id: 17,
    dsatopic: "Array-III",
    problem: "Reverse Pairs",
    Done: "<->",
    URL: "https://leetcode.com/problems/reverse-pairs/",
  },
  {
    id: 18,
    dsatopic: "Array-IV",
    problem: "2-Sum-Problem",
    Done: "<->",
    URL: "https://leetcode.com/problems/two-sum/",
  },
  {
    id: 19,
    dsatopic: "Array-IV",
    problem: "4-sum-Problem",
    Done: "<->",
    URL: "https://leetcode.com/problems/4sum/",
  },
  {
    id: 20,
    dsatopic: "Array-IV",
    problem: "Longest Consecutive Sequence",
    Done: "<->",
    URL: "https://leetcode.com/problems/longest-consecutive-sequence/",
  },
  {
    id: 21,
    dsatopic: "Array-IV",
    problem: "Largest Subarray with 0 sum",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1",
  },
  {
    id: 22,
    dsatopic: "Array-IV",
    problem: "Count number of subarrays with given Xor K",
    Done: "<->",
    URL: "https://www.interviewbit.com/problems/subarray-with-given-xor/",
  },
  {
    id: 23,
    dsatopic: "Array-IV",
    problem: "Longest Substring Without Repeating Characters",
    Done: "<->",
    URL: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
  },
  {
    id: 24,
    dsatopic: "Linked List-I",
    problem: "Reverse a LinkedList",
    Done: "<->",
    URL: "https://leetcode.com/problems/reverse-linked-list/",
  },
  {
    id: 25,
    dsatopic: "Linked List-I",
    problem: "	Find the middle of LinkedList",
    Done: "<->",
    URL: "https://leetcode.com/problems/middle-of-the-linked-list/",
  },
  {
    id: 26,
    dsatopic: "Linked List-I",
    problem: "Merge two sorted Linked List (use method used in mergeSort)",
    Done: "<->",
    URL: "https://leetcode.com/problems/merge-two-sorted-lists/",
  },
  {
    id: 27,
    dsatopic: "Linked List-I",
    problem: "Remove N-th node from back of LinkedList",
    Done: "<->",
    URL: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
  },
  {
    id: 28,
    dsatopic: "Linked List-I",
    problem: "Add two numbers as LinkedList",
    Done: "<->",
    URL: "https://leetcode.com/problems/add-two-numbers/",
  },
  {
    id: 29,
    dsatopic: "Linked List-I",
    problem: "Delete a given Node when a node is given.(0(1) solution)",
    Done: "<->",
    URL: "https://leetcode.com/problems/delete-node-in-a-linked-list/",
  },
  {
    id: 30,
    dsatopic: "Linked List-II",
    problem: "Find intersection point of Y LinkedList",
    Done: "<->",
    URL: "https://leetcode.com/problems/intersection-of-two-linked-lists/",
  },
  {
    id: 31,
    dsatopic: "Linked List-II",
    problem: "Detect a cycle in Linked List",
    Done: "<->",
    URL: "https://leetcode.com/problems/linked-list-cycle/",
  },
  {
    id: 32,
    dsatopic: "Linked List-II",
    problem: "Reverse a LinkedList in groups of size k.",
    Done: "<->",
    URL: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
  },
  {
    id: 33,
    dsatopic: "Linked List-II",
    problem: "Check if a LinkedList is palindrome or not.",
    Done: "<->",
    URL: "https://leetcode.com/problems/palindrome-linked-list/",
  },
  {
    id: 34,
    dsatopic: "Linked List-II",
    problem: "Find the starting point of the Loop of LinkedList",
    Done: "<->",
    URL: "https://leetcode.com/problems/linked-list-cycle-ii/",
  },
  {
    id: 35,
    dsatopic: "Linked List-II",
    problem: "	Flattening of a LinkedList",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1",
  }, 
  {
    id: 36,
    dsatopic: "Linked List and Arrays",
    problem: "Write a program to cyclically rotate an array by one.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one/0",
  },
  {
    id: 37,
    dsatopic: "Linked List and Arrays",
    problem: "Write a program to cyclically rotate an array by one.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one/0",
  },
  {
    id: 38,
    dsatopic: "Linked List and Arrays",
    problem: "Write a program to cyclically rotate an array by one.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one/0",
  },
  {
    id: 39,
    dsatopic: "Linked List and Arrays",
    problem: "Write a program to cyclically rotate an array by one.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one/0",
  },
  {
    id: 40,
    dsatopic: "Linked List and Arrays",
    problem: "Write a program to cyclically rotate an array by one.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one/0",
  },
  {
    id: 41,
    dsatopic: "Linked List and Arrays",
    problem: "Write a program to cyclically rotate an array by one.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one/0",
  },
  {
    id: 42,
    dsatopic: "Greedy Algorithm",
    problem: "find Largest sum contiguous Subarray [V. IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
  },
  {
    id: 43,
    dsatopic: "Greedy Algorithm",
    problem: "find Largest sum contiguous Subarray [V. IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
  },
  {
    id: 44,
    dsatopic: "Greedy Algorithm",
    problem: "find Largest sum contiguous Subarray [V. IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
  },
  {
    id: 45,
    dsatopic: "Greedy Algorithm",
    problem: "find Largest sum contiguous Subarray [V. IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
  },
  {
    id: 46,
    dsatopic: "Greedy Algorithm",
    problem: "find Largest sum contiguous Subarray [V. IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
  },
  {
    id: 47,
    dsatopic: "Greedy Algorithm",
    problem: "find Largest sum contiguous Subarray [V. IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
  },
  {
    id: 48,
    dsatopic: "Recursion",
    problem: "Minimise the maximum difference between heights [V.IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimize-the-heights3351/1",
  },
  {
    id: 49,
    dsatopic: "Recursion",
    problem: "Minimise the maximum difference between heights [V.IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimize-the-heights3351/1",
  },
  {
    id: 50,
    dsatopic: "Recursion",
    problem: "Minimise the maximum difference between heights [V.IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimize-the-heights3351/1",
  },
  {
    id: 51,
    dsatopic: "Recursion",
    problem: "Minimise the maximum difference between heights [V.IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimize-the-heights3351/1",
  },
  {
    id: 52,
    dsatopic: "Recursion",
    problem: "Minimise the maximum difference between heights [V.IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimize-the-heights3351/1",
  },
  {
    id: 53,
    dsatopic: "Recursion",
    problem: "Minimise the maximum difference between heights [V.IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimize-the-heights3351/1",
  },
  {
    id: 54,
    dsatopic: "Recursion and Backtracking",
    problem: "Minimum no. of Jumps to reach end of an array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0",
  },
  {
    id: 55,
    dsatopic: "Recursion and Backtracking",
    problem: "Minimum no. of Jumps to reach end of an array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0",
  },
  {
    id: 56,
    dsatopic: "Recursion and Backtracking",
    problem: "Minimum no. of Jumps to reach end of an array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0",
  },
  {
    id: 57,
    dsatopic: "Recursion and Backtracking",
    problem: "Minimum no. of Jumps to reach end of an array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0",
  },
  {
    id: 58,
    dsatopic: "Recursion and Backtracking",
    problem: "Minimum no. of Jumps to reach end of an array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0",
  },
  {
    id: 59,
    dsatopic: "Recursion and Backtracking",
    problem: "Minimum no. of Jumps to reach end of an array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/minimum-number-of-jumps/0",
  },
  {
    id: 60,
    dsatopic: "Binary Search",
    problem: "find duplicate in an array of N+1 Integers",
    Done: "<->",
    URL: "https://leetcode.com/problems/find-the-duplicate-number/",
  },
  {
    id: 61,
    dsatopic: "Binary Search",
    problem: "find duplicate in an array of N+1 Integers",
    Done: "<->",
    URL: "https://leetcode.com/problems/find-the-duplicate-number/",
  },
  {
    id: 62,
    dsatopic: "Binary Search",
    problem: "find duplicate in an array of N+1 Integers",
    Done: "<->",
    URL: "https://leetcode.com/problems/find-the-duplicate-number/",
  },
  {
    id: 63,
    dsatopic: "Binary Search",
    problem: "find duplicate in an array of N+1 Integers",
    Done: "<->",
    URL: "https://leetcode.com/problems/find-the-duplicate-number/",
  },
  {
    id: 64,
    dsatopic: "Binary Search",
    problem: "find duplicate in an array of N+1 Integers",
    Done: "<->",
    URL: "https://leetcode.com/problems/find-the-duplicate-number/",
  },
  {
    id: 65,
    dsatopic: "Binary Search",
    problem: "find duplicate in an array of N+1 Integers",
    Done: "<->",
    URL: "https://leetcode.com/problems/find-the-duplicate-number/",
  },
  {
    id: 66,
    dsatopic: "Binary Search",
    problem: "find duplicate in an array of N+1 Integers",
    Done: "<->",
    URL: "https://leetcode.com/problems/find-the-duplicate-number/",
  },
  {
    id: 67,
    dsatopic: "Binary Search",
    problem: "find duplicate in an array of N+1 Integers",
    Done: "<->",
    URL: "https://leetcode.com/problems/find-the-duplicate-number/",
  },
  {
    id: 68,
    dsatopic: "Heaps",
    problem: "Merge 2 sorted arrays without using Extra space.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays5135/1",
  },
  {
    id: 69,
    dsatopic: "Heaps",
    problem: "Merge 2 sorted arrays without using Extra space.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays5135/1",
  },
  {
    id: 70,
    dsatopic: "Heaps",
    problem: "Merge 2 sorted arrays without using Extra space.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays5135/1",
  },
  {
    id: 71,
    dsatopic: "Heaps",
    problem: "Merge 2 sorted arrays without using Extra space.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays5135/1",
  },
  {
    id: 72,
    dsatopic: "Heaps",
    problem: "Merge 2 sorted arrays without using Extra space.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays5135/1",
  },
  {
    id: 73,
    dsatopic: "Heaps",
    problem: "Merge 2 sorted arrays without using Extra space.",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays5135/1",
  },
  {
    id: 74,
    dsatopic: "Stack and Queue-I",
    problem: "Kadane's Algo [V.V.V.V.V IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
  },
  {
    id: 75,
    dsatopic: "Stack and Queue-I",
    problem: "Kadane's Algo [V.V.V.V.V IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
  },
  {
    id: 76,
    dsatopic: "Stack and Queue-I",
    problem: "Kadane's Algo [V.V.V.V.V IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
  },
  {
    id: 77,
    dsatopic: "Stack and Queue-I",
    problem: "Kadane's Algo [V.V.V.V.V IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
  },
  {
    id: 78,
    dsatopic: "Stack and Queue-I",
    problem: "Kadane's Algo [V.V.V.V.V IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
  },
  {
    id: 79,
    dsatopic: "Stack and Queue-I",
    problem: "Kadane's Algo [V.V.V.V.V IMP]",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/kadanes-algorithm/0",
  },
  {
    id: 80,
    dsatopic: "Stack and Queue-II",
    problem: "Merge Intervals",
    Done: "<->",
    URL: "https://leetcode.com/problems/merge-intervals/",
  },
  {
    id: 81,
    dsatopic: "Stack and Queue-II",
    problem: "Merge Intervals",
    Done: "<->",
    URL: "https://leetcode.com/problems/merge-intervals/",
  },
  {
    id: 82,
    dsatopic: "Stack and Queue-II",
    problem: "Merge Intervals",
    Done: "<->",
    URL: "https://leetcode.com/problems/merge-intervals/",
  },
  {
    id: 83,
    dsatopic: "Stack and Queue-II",
    problem: "Merge Intervals",
    Done: "<->",
    URL: "https://leetcode.com/problems/merge-intervals/",
  },
  {
    id: 84,
    dsatopic: "Stack and Queue-II",
    problem: "Merge Intervals",
    Done: "<->",
    URL: "https://leetcode.com/problems/merge-intervals/",
  },
  {
    id: 85,
    dsatopic: "Stack and Queue-II",
    problem: "Merge Intervals",
    Done: "<->",
    URL: "https://leetcode.com/problems/merge-intervals/",
  },
  {
    id: 86,
    dsatopic: "String-I",
    problem: "Next Permutation",
    Done: "<->",
    URL: "https://leetcode.com/problems/next-permutation/",
  },
  {
    id: 87,
    dsatopic: "String-I",
    problem: "Next Permutation",
    Done: "<->",
    URL: "https://leetcode.com/problems/next-permutation/",
  },
  {
    id: 88,
    dsatopic: "String-I",
    problem: "Next Permutation",
    Done: "<->",
    URL: "https://leetcode.com/problems/next-permutation/",
  },
  {
    id: 89,
    dsatopic: "String-I",
    problem: "Next Permutation",
    Done: "<->",
    URL: "https://leetcode.com/problems/next-permutation/",
  },
  {
    id: 90,
    dsatopic: "String-I",
    problem: "Next Permutation",
    Done: "<->",
    URL: "https://leetcode.com/problems/next-permutation/",
  },
  {
    id: 91,
    dsatopic: "String-I",
    problem: "Next Permutation",
    Done: "<->",
    URL: "https://leetcode.com/problems/next-permutation/",
  },
  {
    id: 92,
    dsatopic: "String-II",
    problem: "Count Inversion",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/inversion-of-array/0",
  },
  {
    id: 93,
    dsatopic: "String-II",
    problem: "Count Inversion",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/inversion-of-array/0",
  },
  {
    id: 94,
    dsatopic: "String-II",
    problem: "Count Inversion",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/inversion-of-array/0",
  },
  {
    id: 95,
    dsatopic: "String-II",
    problem: "Count Inversion",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/inversion-of-array/0",
  },
  {
    id: 96,
    dsatopic: "String-II",
    problem: "Count Inversion",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/inversion-of-array/0",
  },
  {
    id: 97,
    dsatopic: "String-II",
    problem: "Count Inversion",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/inversion-of-array/0",
  },
  {
    id: 98,
    dsatopic: "Binary Tree-I",
    problem: "Best time to buy and Sell stock",
    Done: "<->",
    URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
  },
  {
    id: 99,
    dsatopic: "Binary Tree-I",
    problem: "Best time to buy and Sell stock",
    Done: "<->",
    URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
  },
  {
    id: 100,
    dsatopic: "Binary Tree-I",
    problem: "Best time to buy and Sell stock",
    Done: "<->",
    URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
  },
  {
    id: 101,
    dsatopic: "Binary Tree-I",
    problem: "Best time to buy and Sell stock",
    Done: "<->",
    URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
  },
  {
    id: 102,
    dsatopic: "Binary Tree-I",
    problem: "Best time to buy and Sell stock",
    Done: "<->",
    URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
  },
  {
    id: 103,
    dsatopic: "Binary Tree-I",
    problem: "Best time to buy and Sell stock",
    Done: "<->",
    URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
  },
  {
    id: 104,
    dsatopic: "Binary Tree-II",
    problem:
      "find all pairs on integer array whose sum is equal to given number",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/count-pairs-with-given-sum5022/1",
  },
  {
    id: 105,
    dsatopic: "Binary Tree-II",
    problem:
      "find all pairs on integer array whose sum is equal to given number",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/count-pairs-with-given-sum5022/1",
  },
  {
    id: 106,
    dsatopic: "Binary Tree-II",
    problem:
      "find all pairs on integer array whose sum is equal to given number",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/count-pairs-with-given-sum5022/1",
  },
  {
    id: 107,
    dsatopic: "Binary Tree-II",
    problem:
      "find all pairs on integer array whose sum is equal to given number",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/count-pairs-with-given-sum5022/1",
  },
  {
    id: 108,
    dsatopic: "Binary Tree-II",
    problem:
      "find all pairs on integer array whose sum is equal to given number",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/count-pairs-with-given-sum5022/1",
  },
  {
    id: 109,
    dsatopic: "Binary Tree-II",
    problem:
      "find all pairs on integer array whose sum is equal to given number",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/count-pairs-with-given-sum5022/1",
  },
  {
    id: 110,
    dsatopic: "Binary Tree-III",
    problem: "find common elements In 3 sorted arrays",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/common-elements1132/1",
  },
  {
    id: 111,
    dsatopic: "Binary Tree-III",
    problem: "find common elements In 3 sorted arrays",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/common-elements1132/1",
  },
  {
    id: 112,
    dsatopic: "Binary Tree-III",
    problem: "find common elements In 3 sorted arrays",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/common-elements1132/1",
  },
  {
    id: 113,
    dsatopic: "Binary Tree-III",
    problem: "find common elements In 3 sorted arrays",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/common-elements1132/1",
  },
  {
    id: 114,
    dsatopic: "Binary Tree-III",
    problem: "find common elements In 3 sorted arrays",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/common-elements1132/1",
  },
  {
    id: 115,
    dsatopic: "Binary Tree-III",
    problem: "find common elements In 3 sorted arrays",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/common-elements1132/1",
  },
  {
    id: 116,
    dsatopic: "Binary Search Tree-I",
    problem:
      "Rearrange the array in alternating positive and negative items with O(1) extra space",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/rearrange-array-alternating-positive-negative-items-o1-extra-space/",
  },
  {
    id: 117,
    dsatopic: "Binary Search Tree-I",
    problem:
      "Rearrange the array in alternating positive and negative items with O(1) extra space",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/rearrange-array-alternating-positive-negative-items-o1-extra-space/",
  },
  {
    id: 119,
    dsatopic: "Binary Search Tree-I",
    problem:
      "Rearrange the array in alternating positive and negative items with O(1) extra space",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/rearrange-array-alternating-positive-negative-items-o1-extra-space/",
  },
  {
    id: 120,
    dsatopic: "Binary Search Tree-I",
    problem:
      "Rearrange the array in alternating positive and negative items with O(1) extra space",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/rearrange-array-alternating-positive-negative-items-o1-extra-space/",
  },
  {
    id: 121,
    dsatopic: "Binary Search Tree-I",
    problem:
      "Rearrange the array in alternating positive and negative items with O(1) extra space",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/rearrange-array-alternating-positive-negative-items-o1-extra-space/",
  },
  {
    id: 122,
    dsatopic: "Binary Search Tree-I",
    problem:
      "Rearrange the array in alternating positive and negative items with O(1) extra space",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/rearrange-array-alternating-positive-negative-items-o1-extra-space/",
  },
  {
    id: 123,
    dsatopic: "Binary Search Tree-II",
    problem: "Find if there is any subarray with sum equal to 0",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/subarray-with-0-sum/0",
  },
  {
    id: 124,
    dsatopic: "Binary Search Tree-II",
    problem: "Find if there is any subarray with sum equal to 0",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/subarray-with-0-sum/0",
  },
  {
    id: 125,
    dsatopic: "Binary Search Tree-II",
    problem: "Find if there is any subarray with sum equal to 0",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/subarray-with-0-sum/0",
  },
  {
    id: 126,
    dsatopic: "Binary Search Tree-II",
    problem: "Find if there is any subarray with sum equal to 0",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/subarray-with-0-sum/0",
  },
  {
    id: 127,
    dsatopic: "Binary Search Tree-II",
    problem: "Find if there is any subarray with sum equal to 0",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/subarray-with-0-sum/0",
  },
  {
    id: 128,
    dsatopic: "Binary Search Tree-II",
    problem: "Find if there is any subarray with sum equal to 0",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/subarray-with-0-sum/0",
  },
  {
    id: 129,
    dsatopic: "Binary Search Tree-III",
    problem: "Find factorial of a large number",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/factorials-of-large-numbers/0",
  },
  {
    id: 130,
    dsatopic: "Binary Search Tree-III",
    problem: "Find factorial of a large number",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/factorials-of-large-numbers/0",
  },
  {
    id: 131,
    dsatopic: "Binary Search Tree-III",
    problem: "Find factorial of a large number",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/factorials-of-large-numbers/0",
  },
  {
    id: 132,
    dsatopic: "Binary Search Tree-III",
    problem: "Find factorial of a large number",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/factorials-of-large-numbers/0",
  },
  {
    id: 133,
    dsatopic: "Binary Search Tree-III",
    problem: "Find factorial of a large number",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/factorials-of-large-numbers/0",
  },
  {
    id: 134,
    dsatopic: "Binary Search Tree-III",
    problem: "Find factorial of a large number",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/factorials-of-large-numbers/0",
  },
  {
    id: 135,
    dsatopic: "Graph-I",
    problem: "find maximum product subarray ",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/maximum-product-subarray3604/1",
  },
  {
    id: 136,
    dsatopic: "Graph-I",
    problem: "find maximum product subarray ",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/maximum-product-subarray3604/1",
  },
  {
    id: 137,
    dsatopic: "Graph-I",
    problem: "find maximum product subarray ",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/maximum-product-subarray3604/1",
  },
  {
    id: 138,
    dsatopic: "Graph-I",
    problem: "find maximum product subarray ",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/maximum-product-subarray3604/1",
  },
  {
    id: 139,
    dsatopic: "Graph-I",
    problem: "find maximum product subarray ",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/maximum-product-subarray3604/1",
  },
  {
    id: 140,
    dsatopic: "Graph-I",
    problem: "find maximum product subarray ",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/maximum-product-subarray3604/1",
  },
  {
    id: 141,
    dsatopic: "Graph-II",
    problem: "Find longest coinsecutive subsequence",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-consecutive-subsequence/0",
  },
  {
    id: 142,
    dsatopic: "Graph-II",
    problem: "Find longest coinsecutive subsequence",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-consecutive-subsequence/0",
  },
  {
    id: 143,
    dsatopic: "Graph-II",
    problem: "Find longest coinsecutive subsequence",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-consecutive-subsequence/0",
  },
  {
    id: 144,
    dsatopic: "Graph-II",
    problem: "Find longest coinsecutive subsequence",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-consecutive-subsequence/0",
  },
  {
    id: 145,
    dsatopic: "Graph-II",
    problem: "Find longest coinsecutive subsequence",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-consecutive-subsequence/0",
  },
  {
    id: 146,
    dsatopic: "Graph-II",
    problem: "Find longest coinsecutive subsequence",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/longest-consecutive-subsequence/0",
  },
  {
    id: 147,
    dsatopic: "Dynamic Programming-I",
    problem:
      'Given an array of size n and a number k, fin all elements that appear more than " n/k " times.',
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/given-an-array-of-of-size-n-finds-all-the-elements-that-appear-more-than-nk-times/",
  },
  {
    id: 148,
    dsatopic: "Dynamic Programming-I",
    problem:
      'Given an array of size n and a number k, fin all elements that appear more than " n/k " times.',
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/given-an-array-of-of-size-n-finds-all-the-elements-that-appear-more-than-nk-times/",
  },
  {
    id: 149,
    dsatopic: "Dynamic Programming-I",
    problem:
      'Given an array of size n and a number k, fin all elements that appear more than " n/k " times.',
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/given-an-array-of-of-size-n-finds-all-the-elements-that-appear-more-than-nk-times/",
  },
  {
    id: 150,
    dsatopic: "Dynamic Programming-I",
    problem:
      'Given an array of size n and a number k, fin all elements that appear more than " n/k " times.',
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/given-an-array-of-of-size-n-finds-all-the-elements-that-appear-more-than-nk-times/",
  },
  {
    id: 151,
    dsatopic: "Dynamic Programming-I",
    problem:
      'Given an array of size n and a number k, fin all elements that appear more than " n/k " times.',
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/given-an-array-of-of-size-n-finds-all-the-elements-that-appear-more-than-nk-times/",
  },
  {
    id: 152,
    dsatopic: "Dynamic Programming-I",
    problem:
      'Given an array of size n and a number k, fin all elements that appear more than " n/k " times.',
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/given-an-array-of-of-size-n-finds-all-the-elements-that-appear-more-than-nk-times/",
  },
  {
    id: 153,
    dsatopic: "Dynamic Programming-II",
    problem: "Maximum profit by buying and selling a share atmost twice",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-twice/",
  },
  {
    id: 154,
    dsatopic: "Dynamic Programming-II",
    problem: "Maximum profit by buying and selling a share atmost twice",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-twice/",
  },
  {
    id: 155,
    dsatopic: "Dynamic Programming-II",
    problem: "Maximum profit by buying and selling a share atmost twice",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-twice/",
  },
  {
    id: 156,
    dsatopic: "Dynamic Programming-II",
    problem: "Maximum profit by buying and selling a share atmost twice",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-twice/",
  },
  {
    id: 157,
    dsatopic: "Dynamic Programming-II",
    problem: "Maximum profit by buying and selling a share atmost twice",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-twice/",
  },
  {
    id: 158,
    dsatopic: "Dynamic Programming-II",
    problem: "Maximum profit by buying and selling a share atmost twice",
    Done: "<->",
    URL: "https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-twice/",
  },
  {
    id: 159,
    dsatopic: "Trie",
    problem: "Find whether an array is a subset of another array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/array-subset-of-another-array/0",
  },
  {
    id: 160,
    dsatopic: "Trie",
    problem: "Find whether an array is a subset of another array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/array-subset-of-another-array/0",
  },
  {
    id: 161,
    dsatopic: "Trie",
    problem: "Find whether an array is a subset of another array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/array-subset-of-another-array/0",
  },
  {
    id: 162,
    dsatopic: "Trie",
    problem: "Find whether an array is a subset of another array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/array-subset-of-another-array/0",
  },
  {
    id: 163,
    dsatopic: "Trie",
    problem: "Find whether an array is a subset of another array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/array-subset-of-another-array/0",
  },
  {
    id: 164,
    dsatopic: "Trie",
    problem: "Find whether an array is a subset of another array",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/array-subset-of-another-array/0",
  },
  {
    id: 165,
    dsatopic: "Operating System",
    problem: "Find the triplet that sum to a given value",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/triplet-sum-in-array/0",
  },
  {
    id: 166,
    dsatopic: "DBMS",
    problem: "Trapping Rain water problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/trapping-rain-water/0",
  },
  {
    id: 167,
    dsatopic: "Computer Networks",
    problem: "Chocolate Distribution problem",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/chocolate-distribution-problem/0",
  },
  {
    id: 168,
    dsatopic: "Project Overview",
    problem: "Smallest Subarray with sum greater than a given value",
    Done: "<->",
    URL: "https://practice.geeksforgeeks.org/problems/smallest-subarray-with-sum-greater-than-x/0",
  },
];
